#!/usr/bin/env bash
#
# Generate one of three disposable repos for hands-on flow-code testing:
#
#   engine             local CLI; the user drives `flow-code init` and `run`
#   companion-local    local CLI + local Claude plugin via --plugin-dir
#   companion-release  published CLI + public Claude plugin marketplace
#
# Usage: make-testbed.sh --mode engine|companion-local|companion-release
#                        [--dest PATH] [--no-build]

set -euo pipefail

ROOT_MARKER=.flow-code-testbed
GIT_MARKER=.git/flow-code-testbed

MODE=
DEST=
BUILD=1

while [ $# -gt 0 ]; do
  case "$1" in
    --mode) MODE="$2"; shift 2 ;;
    --dest) DEST="$2"; shift 2 ;;
    --no-build) BUILD=0; shift ;;
    -h|--help) sed -n '3,11p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1 — see --help" >&2; exit 2 ;;
  esac
done

case "$MODE" in
  engine|companion-local|companion-release) ;;
  "") echo "--mode is required: engine, companion-local, or companion-release" >&2; exit 2 ;;
  *) echo "unknown mode: $MODE — expected engine, companion-local, or companion-release" >&2; exit 2 ;;
esac

if [ -z "$DEST" ]; then
  DEST="${HOME}/flow-code-testbed-${MODE}"
fi

if [ "$MODE" = "companion-release" ] && [ "$BUILD" -eq 0 ]; then
  echo "--no-build only applies to engine and companion-local" >&2
  exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
LOCAL_BIN="${DEST}.flow-code-bin"

# Refuse every deletion unless the target carries a marker written by this
# script. Plugin-installed project files deliberately carry that marker under
# .git, where an ordinary user's worktree cannot see it.
if [ -e "$DEST" ]; then
  if [ ! -f "$DEST/$ROOT_MARKER" ] && [ ! -f "$DEST/$GIT_MARKER" ]; then
    echo "refusing to replace $DEST: it exists and is not a testbed" >&2
    echo "(no testbed marker). Move it aside, or pass a different --dest." >&2
    exit 1
  fi
fi

if [ "$MODE" != "companion-release" ] && [ -e "$LOCAL_BIN" ] && [ ! -f "$LOCAL_BIN/$ROOT_MARKER" ]; then
  echo "refusing to replace $LOCAL_BIN: it is not a testbed shim" >&2
  echo "(no $ROOT_MARKER file). Move it aside, or pass a different --dest." >&2
  exit 1
fi

# A release test must not inherit a shim previously generated for this path.
# Remove only a marked shim, then require the user's published installation.
if [ "$MODE" = "companion-release" ]; then
  if [ -f "$LOCAL_BIN/$ROOT_MARKER" ]; then
    rm -rf "$LOCAL_BIN"
  fi
  RELEASE_BIN="$(command -v flow-code || true)"
  if [ -z "$RELEASE_BIN" ]; then
    echo "companion-release requires the published flow-code CLI on PATH." >&2
    echo "Install it first: npm install -g @easonliuuuuu/flow-code" >&2
    echo "The release mode never substitutes this checkout's dist/ build." >&2
    exit 1
  fi
  RELEASE_REAL="$(readlink -f "$RELEASE_BIN" 2>/dev/null || echo "$RELEASE_BIN")"
  case "$RELEASE_BIN:$RELEASE_REAL" in
    *"$REPO_ROOT"*|*.flow-code-bin/flow-code*)
      echo "companion-release resolved flow-code to a local development build:" >&2
      echo "  $RELEASE_BIN" >&2
      echo "Install the published CLI and remove the local shim from PATH." >&2
      exit 1
      ;;
  esac
fi

if [ -e "$DEST" ]; then
  rm -rf "$DEST"
fi

if [ "$MODE" != "companion-release" ]; then
  if [ "$BUILD" -eq 1 ]; then
    echo "building $REPO_ROOT ..."
    ( cd "$REPO_ROOT" && npm run build >/dev/null )
  fi
  if [ -e "$LOCAL_BIN" ]; then
    rm -rf "$LOCAL_BIN"
  fi
  mkdir -p "$LOCAL_BIN"
  cat > "$LOCAL_BIN/$ROOT_MARKER" <<EOF
Generated by flow-code's testbed skill for $DEST. This directory exposes the
current checkout's CLI without putting a shim inside the generated repository.
EOF
  cat > "$LOCAL_BIN/flow-code" <<EOF
#!/usr/bin/env bash
exec node "$REPO_ROOT/dist/cli.js" "\$@"
EOF
  chmod +x "$LOCAL_BIN/flow-code"
fi

mkdir -p "$DEST"
cd "$DEST"

cat > "$ROOT_MARKER" <<EOF
Generated by flow-code's testbed skill (mode: $MODE). This marker moves under
.git before the initial commit so the generated worktree stays ordinary.
EOF

git init -q -b main
git config user.email "$(git -C "$REPO_ROOT" config user.email || echo test@test)"
git config user.name "$(git -C "$REPO_ROOT" config user.name || echo test)"
mv "$ROOT_MARKER" "$GIT_MARKER"

if [ "$MODE" = "engine" ]; then
  cat > README.md <<'EOF'
# Engine test project

An otherwise-empty Git repository for testing flow-code's first-run path.
There is deliberately no `.flow-code/` directory: start with `flow-code init`,
then use `flow-code run` to exercise the local engine build.
EOF

  git add -A
  git commit -qm "chore: scaffold engine test project"

  echo
  echo "testbed ready: $DEST  (mode: engine, source: local checkout)"
  echo
  echo "Run in a real terminal:"
  echo
  echo "  cd $DEST"
  echo "  export PATH=\"$LOCAL_BIN:\$PATH\""
  echo "  flow-code init"
  echo "  flow-code run"
  echo
  echo "The exported flow-code command points at $REPO_ROOT/dist/cli.js."
  echo "The run calls a real provider and costs actual API usage."
  exit 0
fi

mkdir -p .flow-code src test

cat > package.json <<'EOF'
{
  "name": "flow-code-companion-testbed",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "test": "node --test"
  }
}
EOF

cat > src/greet.js <<'EOF'
export function greet(name) {
  return `hello ${name}`;
}
EOF

cat > test/greet.test.js <<'EOF'
import assert from 'node:assert/strict';
import test from 'node:test';
import { greet } from '../src/greet.js';

test('greets by name', () => {
  assert.equal(greet('world'), 'hello world');
});
EOF

cat > .flow-code/workflow.yaml <<'EOF'
settings:
  model: sonnet

nodes:
  - id: implement
    type: implement
    config:
      instructions: Make greet handle an empty name, and cover it with a test.

  - id: unit
    type: test
    config:
      commands: ["npm test"]

  - id: review
    type: review

  - id: gate
    type: approval-gate

  - id: ship
    type: git-ops

edges:
  - { from: implement, to: unit }
  - { from: unit, to: review }
  - { from: review, to: gate }
  - { from: gate, to: ship }
  - { from: unit, to: implement, loopback: true }
EOF

cat > README.md <<EOF
# Companion test project

An ordinary project with a flow-code workflow and no per-project integration
files. Mode: $MODE.

The companion session must create the run through the plugin. Start \`watch\`
first so the graph is already waiting when that run appears.
EOF

# Runtime state belongs to this disposable repo but not to its worktree. This
# mirrors flow-code's own exclusion list without invoking either implementation
# while the release/local boundary is being established.
cat >> .git/info/exclude <<'EOF'

# added by flow-code testbed
.flow-code/runs/
.flow-code/worktrees/
.flow-code/reconcile/
.flow-code/enforcement.json
.flow-code/credentials.json
EOF

if [ "$MODE" = "companion-local" ]; then
  PATH="$LOCAL_BIN:$PATH" flow-code validate >/dev/null
else
  flow-code validate >/dev/null
fi

git add -A
git commit -qm "chore: scaffold $MODE test project"

echo
if [ "$MODE" = "companion-local" ]; then
  echo "testbed ready: $DEST  (mode: companion-local, source: local checkout)"
  echo
  echo "Watch it in one terminal:"
  echo
  echo "  cd $DEST"
  echo "  export PATH=\"$LOCAL_BIN:\$PATH\""
  echo "  flow-code watch"
  echo
  echo "Drive it from a second terminal:"
  echo
  echo "  cd $DEST"
  echo "  export PATH=\"$LOCAL_BIN:\$PATH\""
  echo "  claude --plugin-dir $REPO_ROOT/plugin"
  echo
  echo "  # then, in that session:"
  echo "  /flow-code make greet handle an empty name"
  echo
  echo "Both the CLI/MCP server and Claude plugin come from this checkout."
else
  RELEASE_VERSION="$(flow-code --version)"
  echo "testbed ready: $DEST  (mode: companion-release, source: published release $RELEASE_VERSION)"
  echo
  echo "Watch it in one terminal:"
  echo
  echo "  cd $DEST"
  echo "  flow-code watch"
  echo
  echo "Drive it from a second terminal:"
  echo
  echo "  cd $DEST"
  echo "  claude"
  echo
  echo "  # then, in that session:"
  echo "  /plugin marketplace add Easonliuuuuu/flow-code"
  echo "  /plugin install flow-code"
  echo "  # exit Claude, restart it from the same shell, then:"
  echo "  /flow-code make greet handle an empty name"
  echo
  echo "No command or plugin in this mode points at $REPO_ROOT."
fi
echo
echo "This mode runs a real agent session against a real provider — it costs"
echo "actual API usage, and the ship node commits inside the testbed."
