#!/usr/bin/env bash
#
# Generate one of three disposable repos for hands-on flow-code testing:
#
#   engine             local CLI; the user drives `flow-code init` and `run`
#   companion-local    local CLI + Claude plugin or Codex project integration
#   companion-release  published CLI + Claude plugin or Codex project integration
#
# Usage: make-testbed.sh --mode engine|companion-local|companion-release
#                        [--host claude|codex] [--dest PATH] [--no-build]

set -euo pipefail

ROOT_MARKER=.flow-code-testbed
GIT_MARKER=.git/flow-code-testbed

MODE=
HOST=claude
HOST_SET=0
DEST=
BUILD=1

while [ $# -gt 0 ]; do
  case "$1" in
    --mode) MODE="$2"; shift 2 ;;
    --host) HOST="$2"; HOST_SET=1; shift 2 ;;
    --dest) DEST="$2"; shift 2 ;;
    --no-build) BUILD=0; shift ;;
    -h|--help) sed -n '3,11p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1 — see --help" >&2; exit 2 ;;
  esac
done

case "$MODE" in
  engine|companion-local|companion-release) ;;
  "") echo "--mode is required: engine, companion-local, or companion-release" >&2; exit 2 ;;
  *) echo "unknown mode: $MODE — expected engine, companion-local, or companion-release" >&2; exit 2 ;;
esac

case "$HOST" in
  claude|codex) ;;
  *) echo "unknown host: $HOST — expected claude or codex" >&2; exit 2 ;;
esac

if [ "$MODE" = "engine" ] && [ "$HOST_SET" -eq 1 ]; then
  echo "--host only applies to companion-local and companion-release" >&2
  exit 2
fi

if [ -z "$DEST" ]; then
  if [ "$MODE" = "engine" ] || [ "$HOST" = "claude" ]; then
    DEST="${HOME}/flow-code-testbed-${MODE}"
  else
    DEST="${HOME}/flow-code-testbed-companion-codex-${MODE#companion-}"
  fi
fi

if [ "$MODE" = "companion-release" ] && [ "$BUILD" -eq 0 ]; then
  echo "--no-build only applies to engine and companion-local" >&2
  exit 2
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_BIN="${DEST}.flow-code-bin"

# Refuse every deletion unless the target carries a marker written by this
# script. Plugin-installed project files deliberately carry that marker under
# .git, where an ordinary user's worktree cannot see it.
if [ -e "$DEST" ]; then
  if [ ! -f "$DEST/$ROOT_MARKER" ] && [ ! -f "$DEST/$GIT_MARKER" ]; then
    echo "refusing to replace $DEST: it exists and is not a testbed" >&2
    echo "(no testbed marker). Move it aside, or pass a different --dest." >&2
    exit 1
  fi
fi

if [ "$MODE" != "companion-release" ] && [ -e "$LOCAL_BIN" ] && [ ! -f "$LOCAL_BIN/$ROOT_MARKER" ]; then
  echo "refusing to replace $LOCAL_BIN: it is not a testbed shim" >&2
  echo "(no $ROOT_MARKER file). Move it aside, or pass a different --dest." >&2
  exit 1
fi

# A release test must not inherit a shim previously generated for this path.
# Remove only a marked shim, then require the user's published installation.
if [ "$MODE" = "companion-release" ]; then
  if [ -f "$LOCAL_BIN/$ROOT_MARKER" ]; then
    rm -rf "$LOCAL_BIN"
  fi
  RELEASE_BIN="$(command -v flow-code || true)"
  if [ -z "$RELEASE_BIN" ]; then
    echo "companion-release requires the published flow-code CLI on PATH." >&2
    echo "Install it first: npm install -g @easonliuuuuu/flow-code" >&2
    echo "The release mode never substitutes this checkout's dist/ build." >&2
    exit 1
  fi
  RELEASE_REAL="$(readlink -f "$RELEASE_BIN" 2>/dev/null || echo "$RELEASE_BIN")"
  case "$RELEASE_BIN:$RELEASE_REAL" in
    *"$REPO_ROOT"*|*.flow-code-bin/flow-code*)
      echo "companion-release resolved flow-code to a local development build:" >&2
      echo "  $RELEASE_BIN" >&2
      echo "Install the published CLI and remove the local shim from PATH." >&2
      exit 1
      ;;
  esac
  if [ "$HOST" = "codex" ]; then
    RELEASE_HELP="$(flow-code help)"
    case "$RELEASE_HELP" in
      *'--host claude|codex|all'*) ;;
      *)
        echo "companion-release --host codex requires a published flow-code release with Codex companion support." >&2
        echo "The flow-code executable on PATH does not advertise --host claude|codex|all." >&2
        exit 1
        ;;
    esac
  fi
fi

if [ -e "$DEST" ]; then
  rm -rf "$DEST"
fi

if [ "$MODE" != "companion-release" ]; then
  if [ "$BUILD" -eq 1 ]; then
    echo "building $REPO_ROOT ..."
    ( cd "$REPO_ROOT" && npm run build >/dev/null )
  fi
  if [ -e "$LOCAL_BIN" ]; then
    rm -rf "$LOCAL_BIN"
  fi
  mkdir -p "$LOCAL_BIN"
  cat > "$LOCAL_BIN/$ROOT_MARKER" <<EOF
Generated by flow-code's testbed skill for $DEST. This directory exposes the
current checkout's CLI without putting a shim inside the generated repository.
EOF
  cat > "$LOCAL_BIN/flow-code" <<EOF
#!/usr/bin/env bash
exec node "$REPO_ROOT/dist/cli.js" "\$@"
EOF
  chmod +x "$LOCAL_BIN/flow-code"
fi

mkdir -p "$DEST"
cd "$DEST"

cat > "$ROOT_MARKER" <<EOF
Generated by flow-code's testbed skill (mode: $MODE). This marker moves under
.git before the initial commit so the generated worktree stays ordinary.
EOF

git init -q -b main
git config user.email "$(git -C "$REPO_ROOT" config user.email || echo test@test)"
git config user.name "$(git -C "$REPO_ROOT" config user.name || echo test)"
mv "$ROOT_MARKER" "$GIT_MARKER"

if [ "$MODE" = "engine" ]; then
  cat > README.md <<'EOF'
# Engine test project

An otherwise-empty Git repository for testing flow-code's first-run path.
There is deliberately no `.flow-code/` directory: start with `flow-code init`,
then use `flow-code run` to exercise the local engine build.
EOF

  git add -A
  git commit -qm "chore: scaffold engine test project"

  echo
  echo "testbed ready: $DEST  (mode: engine, source: local checkout)"
  echo
  echo "Run in a real terminal:"
  echo
  echo "  cd $DEST"
  echo "  export PATH=\"$LOCAL_BIN:\$PATH\""
  echo "  flow-code init"
  echo "  flow-code run"
  echo
  echo "The exported flow-code command points at $REPO_ROOT/dist/cli.js."
  echo "The run calls a real provider and costs actual API usage."
  exit 0
fi

mkdir -p src test

cat > package.json <<'EOF'
{
  "name": "flow-code-companion-testbed",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "test": "node --test"
  }
}
EOF

cat > src/greet.js <<'EOF'
export function greet(name) {
  return `hello ${name}`;
}
EOF

cat > test/greet.test.js <<'EOF'
import assert from 'node:assert/strict';
import test from 'node:test';
import { greet } from '../src/greet.js';

test('greets by name', () => {
  assert.equal(greet('world'), 'hello world');
});
EOF

if [ "$HOST" = "claude" ]; then
cat > README.md <<EOF
# Companion test project

An ordinary project with no flow-code configuration yet and no per-project
integration files. Mode: $MODE; host: Claude Code.

This project has no \`.flow-code/workflow.yaml\`. In the companion session,
either name one of the built-in presets (openspec, spec-kit, frugal, planned)
or run \`flow-code init\` first to scaffold this project's own workflow, then
say what you actually want built. Start \`watch\` first so the graph is
already waiting when a run appears.
EOF
else
cat > README.md <<EOF
# Companion test project

An ordinary project prepared for flow-code's Codex companion mode. Mode:
$MODE; host: Codex.

The default workflow and Codex project integration are committed as part of
the fixture. Start \`watch\` first so the graph is already waiting when a run
appears, then launch a new Codex session and describe what you want built.
EOF
fi

# Runtime state belongs to this disposable repo but not to its worktree. This
# mirrors flow-code's own exclusion list without invoking either implementation
# while the release/local boundary is being established.
cat >> .git/info/exclude <<'EOF'

# added by flow-code testbed
.flow-code/runs/
.flow-code/worktrees/
.flow-code/reconcile/
.flow-code/enforcement.json
.flow-code/credentials.json
EOF

if [ "$HOST" = "codex" ]; then
  if [ "$MODE" = "companion-local" ]; then
    SETUP_BIN="$LOCAL_BIN/flow-code"
    PATH="$LOCAL_BIN:$PATH" "$SETUP_BIN" init </dev/null >/dev/null
    PATH="$LOCAL_BIN:$PATH" "$SETUP_BIN" connect --host codex >/dev/null
  else
    flow-code init </dev/null >/dev/null
    flow-code connect --host codex >/dev/null
  fi
fi

git add -A
git commit -qm "chore: scaffold $HOST $MODE test project"

echo
if [ "$HOST" = "codex" ]; then
  if [ "$MODE" = "companion-local" ]; then
    SOURCE_LABEL="local checkout"
    PATH_LINE="  export PATH=\"$LOCAL_BIN:\$PATH\""
  else
    RELEASE_VERSION="$(flow-code --version)"
    SOURCE_LABEL="published release $RELEASE_VERSION"
    PATH_LINE=
  fi
  echo "testbed ready: $DEST  (mode: $MODE, host: codex, source: $SOURCE_LABEL)"
  echo
  echo "Verify the generated project integration:"
  echo
  echo "  cd $DEST"
  if [ -n "$PATH_LINE" ]; then echo "$PATH_LINE"; fi
  echo "  flow-code connect --host codex --check"
  echo
  echo "Watch it in one terminal:"
  echo
  echo "  cd $DEST"
  if [ -n "$PATH_LINE" ]; then echo "$PATH_LINE"; fi
  echo "  flow-code watch"
  echo
  echo "Drive it from a second terminal:"
  echo
  echo "  cd $DEST"
  if [ -n "$PATH_LINE" ]; then echo "$PATH_LINE"; fi
  echo "  codex"
  echo
  echo "  # review and trust the project hook if prompted, then inspect:"
  echo "  # /hooks"
  echo "  # /mcp"
  echo "  # describe what you want built; the default workflow is installed"
  if [ "$MODE" = "companion-local" ]; then
    echo
    echo "The CLI/MCP server, hook, and generated integration come from this checkout."
  else
    echo
    echo "No command or generated integration in this mode points at $REPO_ROOT."
  fi
elif [ "$MODE" = "companion-local" ]; then
  echo "testbed ready: $DEST  (mode: companion-local, source: local checkout)"
  echo
  echo "Watch it in one terminal:"
  echo
  echo "  cd $DEST"
  echo "  export PATH=\"$LOCAL_BIN:\$PATH\""
  echo "  flow-code watch"
  echo
  echo "Drive it from a second terminal:"
  echo
  echo "  cd $DEST"
  echo "  export PATH=\"$LOCAL_BIN:\$PATH\""
  echo "  claude --plugin-dir $REPO_ROOT/plugin"
  echo
  echo "  # then: /flow-code <describe what you want>"
  echo "  # there is no .flow-code/workflow.yaml yet, so the agent should ask"
  echo "  # what workflow you want: a named preset (openspec, spec-kit,"
  echo "  # frugal, planned) for just this run, or 'flow-code init' for a"
  echo "  # persistent one — and scaffold the latter itself via Bash, not"
  echo "  # hand the command back to you."
  echo
  echo "Both the CLI/MCP server and Claude plugin come from this checkout."
else
  RELEASE_VERSION="$(flow-code --version)"
  echo "testbed ready: $DEST  (mode: companion-release, source: published release $RELEASE_VERSION)"
  echo
  echo "Watch it in one terminal:"
  echo
  echo "  cd $DEST"
  echo "  flow-code watch"
  echo
  echo "Drive it from a second terminal:"
  echo
  echo "  cd $DEST"
  echo "  claude"
  echo
  echo "  # then, in that session:"
  echo "  /plugin marketplace add Easonliuuuuu/flow-code"
  echo "  /plugin install flow-code"
  echo "  # exit Claude, restart it from the same shell, then:"
  echo "  /flow-code <describe what you want>"
  echo "  # there is no .flow-code/workflow.yaml yet, so the agent should ask"
  echo "  # what workflow you want: a named preset (openspec, spec-kit,"
  echo "  # frugal, planned) for just this run, or 'flow-code init' for a"
  echo "  # persistent one — and scaffold the latter itself via Bash, not"
  echo "  # hand the command back to you."
  echo
  echo "No command or plugin in this mode points at $REPO_ROOT."
fi
echo
echo "This mode runs a real agent session against a real provider — it costs"
echo "actual API usage, and its git-ops step commits inside the testbed."
